"""empty message

Revision ID: 547b6306823e
Revises: 
Create Date: 2023-05-19 19:26:33.160308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547b6306823e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('day_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('day')
    # ### end Alembic commands ###
